version: '3.8'

services:
  db:
    container_name: SpringCourse2
    image: postgres
    environment:
      POSTGRES_USER: Wassem
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "1234:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: